# Generated by Django 4.2 on 2023-05-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id_album",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id_artist",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("popularity", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MusicGenre",
            fields=[
                ("id_genre", models.AutoField(primary_key=True, serialize=False)),
                ("genre_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id_playlist",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id_session", models.IntegerField(primary_key=True, serialize=False)),
                ("session_code", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id_track",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("album", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id_user",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("id_spotify", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("access_token", models.CharField(max_length=255)),
                ("token_type", models.CharField(max_length=255)),
                ("expires_in", models.DateTimeField()),
                ("refresh_token", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SessionMembers",
            fields=[
                ("id_member", models.IntegerField(primary_key=True, serialize=False)),
                ("joined_at", models.DateTimeField()),
                (
                    "id_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.session",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="id_host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_party.user"
            ),
        ),
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.playlist",
                    ),
                ),
                (
                    "id_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playlist",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_party.user"
            ),
        ),
        migrations.CreateModel(
            name="MusicGenreTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.musicgenre",
                    ),
                ),
                (
                    "id_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="musicgenre",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_party.user"
            ),
        ),
        migrations.CreateModel(
            name="ArtistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.artist",
                    ),
                ),
                (
                    "id_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_party.user"
            ),
        ),
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.album",
                    ),
                ),
                (
                    "id_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spotify_party.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="id_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spotify_party.user"
            ),
        ),
    ]
