# Generated by Django 4.2 on 2023-05-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_party", "0002_room_roomparticipants_room_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RoomParticipants",
            new_name="RoomParticipant",
        ),
    ]
